### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by sirinath** [speedata/ets#2]
I am wondering if your organisation is willing to more to a more liberal license like AL 2.0, MIT, BSD?

This project looks promising. Also following might be of interest: https://sile-typesetter.org, https://tectonic-typesetting.github.io/en-US/

**Comment by pgundlach** [comment]
Hello @sirinath thank you for your comment. 

I am bad at choosing a license for a project. I was thinking about dual licensing the project for AGPL for OpenSource and a paid less restrictive license code. But perhaps this is not a good idea, I don't know. Do you have a reason or a use case for a less restrictive license?

Thank you for the pointers to the projects. I know SILE, which is pretty awesome, but is not suitable for my needs (see for example https://showcase.speedata.de/ for what I need to achieve, I am not sure SILE is the best base for that. I currently use LuaTeX for that. I didn't know about the other one.

**Comment by sirinath** [comment]
I am not sure what license suites you, but more permissive licenses would mean more users would be able to use it especially in commercial settings and embedded use. Some of the commercial users **may** translate to support contact and sponsorship.

**Comment by hmenke** [comment]
Permissive licensing means your code is available to steal.
https://twitter.com/tim_nolet/status/1317061818574082050
Don't forfeit the GPL. It's the only license that truly protected the developer's freedoms.

**Comment by pgundlach** [comment]
I will think about this subject. For now, I'd like to close this issue and would like to thank you for pointing this out.
